export type Contributor = {
  name: string;
  login: string;
  profileUrl: string;
  avatarUrl: string;
  contributions: number;
};

// Generated by scripts/generate-contributors-data.mjs from helmforgedev/charts.
export const chartContributors: Contributor[] = [
  {
    name: 'Maicon Berlofa',
    login: 'mberlofa',
    profileUrl: 'https://github.com/mberlofa',
    avatarUrl: 'https://avatars.githubusercontent.com/u/63069707?v=4&s=96',
    contributions: 596,
  },
  {
    name: 'Mathieu REHO',
    login: 'mreho',
    profileUrl: 'https://github.com/mreho',
    avatarUrl: 'https://avatars.githubusercontent.com/u/25871713?v=4&s=96',
    contributions: 12,
  },
  {
    name: 'ummon-v',
    login: 'ummon-v',
    profileUrl: 'https://github.com/ummon-v',
    avatarUrl: 'https://avatars.githubusercontent.com/u/252456890?v=4&s=96',
    contributions: 3,
  },
  {
    name: 'Volodymyr',
    login: 'volodymyr-devops',
    profileUrl: 'https://github.com/volodymyr-devops',
    avatarUrl: 'https://avatars.githubusercontent.com/u/162500177?v=4&s=96',
    contributions: 2,
  },
  {
    name: 'Dennis Rieks',
    login: 'drieks',
    profileUrl: 'https://github.com/drieks',
    avatarUrl: 'https://avatars.githubusercontent.com/u/861387?v=4&s=96',
    contributions: 1,
  },
  {
    name: 'Radek Crlík',
    login: 'rcrlik',
    profileUrl: 'https://github.com/rcrlik',
    avatarUrl: 'https://avatars.githubusercontent.com/u/46486968?v=4&s=96',
    contributions: 1,
  },
];
